"""first commit

Revision ID: 5de802313f6a
Revises: 
Create Date: 2021-04-04 21:54:24.744624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de802313f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.SMALLINT(), nullable=True),
    sa.Column('birth_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('ancestral_home', sa.String(), nullable=True),
    sa.Column('political_status', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id_card_number', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('face_img_path', sa.String(), nullable=True),
    sa.Column('id_card_path', sa.String(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('is_email_activated', sa.Boolean(), nullable=True),
    sa.Column('is_face_activated', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar_path'),
    sa.UniqueConstraint('face_img_path'),
    sa.UniqueConstraint('id_card_path')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_id_card_number'), 'user', ['id_card_number'], unique=True)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_id_card_number'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
